from __future__ import annotations

import json
import os
import shlex
import shutil
import subprocess
import time
from pathlib import Path

import httpx

from .runtime import rigma_home

RAG_PORT = 11510


def rag_dir() -> Path:
    d = rigma_home() / "rag"
    d.mkdir(parents=True, exist_ok=True)
    return d


def raggity_cmd() -> list[str] | None:
    env = os.environ.get("RIGMA_RAGGITY_CMD")
    if env:
        return shlex.split(env, posix=False)
    exe = shutil.which("raggity")
    return [exe] if exe else None


def load_sources() -> list[str]:
    p = rag_dir() / "sources.json"
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except Exception:
        return []


def _source_globs() -> list[str]:
    globs = []
    for s in load_sources():
        p = Path(s)
        globs.append(f"{p.as_posix()}/**/*" if p.is_dir() else p.as_posix())
    return globs


def write_rag_config(llm_base_url: str = "http://127.0.0.1:11500/v1") -> Path:
    include = ", ".join(json.dumps(g) for g in _source_globs())
    index_path = (rag_dir() / "index").as_posix()
    text = (
        "# generated by rigma — do not edit; edit sources via `rigma rag add`\n"
        'profile = "low-ram"\n\n'
        f"[sources]\ninclude = [{include}]\n\n"
        f'[generation]\nbackend = "external"\nbase_url = "{llm_base_url}"\n\n'
        f'[index]\nbackend = "lancedb"\npath = "{index_path}"\n\n'
        '[server]\nauth = "none"\n'
    )
    cfg = rag_dir() / "raggity.toml"
    cfg.write_text(text, encoding="utf-8")
    return cfg


def add_source(path: str) -> list[str]:
    srcs = load_sources()
    ap = str(Path(path).resolve())
    if ap not in srcs:
        srcs.append(ap)
        (rag_dir() / "sources.json").write_text(json.dumps(srcs, indent=2),
                                                encoding="utf-8")
    write_rag_config()
    return srcs


def sidecar_health(port: int = RAG_PORT) -> dict | None:
    try:
        r = httpx.get(f"http://127.0.0.1:{port}/healthz", timeout=3)
        return r.json() if r.status_code == 200 else None
    except Exception:
        return None


def ensure_sidecar(port: int = RAG_PORT, timeout: float = 90.0) -> dict:
    health = sidecar_health(port)
    if health:
        return health
    cmd = raggity_cmd()
    if cmd is None:
        raise RuntimeError(
            "raggity not found — install with `pip install raggity[server]` "
            "or set RIGMA_RAGGITY_CMD")
    cfg = write_rag_config()
    log_path = rag_dir() / "serve.log"
    with open(log_path, "w", encoding="utf-8", errors="replace") as log_f:
        proc = subprocess.Popen(
            [*cmd, "serve", "--config", str(cfg), "--port", str(port)],
            stdout=log_f, stderr=subprocess.STDOUT)
    (rag_dir() / "sidecar.json").write_text(
        json.dumps({"pid": proc.pid, "port": port}), encoding="utf-8")
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        if proc.poll() is not None:
            break
        health = sidecar_health(port)
        if health:
            return health
        time.sleep(0.5)
    proc.terminate()
    tail = ""
    try:
        tail = "".join(log_path.read_text(encoding="utf-8",
                                          errors="replace").splitlines(True)[-20:])
    except Exception:
        pass
    raise RuntimeError(f"raggity sidecar failed to become healthy on :{port}\n{tail}")


def stop_sidecar() -> bool:
    p = rag_dir() / "sidecar.json"
    try:
        info = json.loads(p.read_text(encoding="utf-8"))
    except Exception:
        return False
    import psutil
    try:
        proc = psutil.Process(int(info["pid"]))
        proc.terminate()
        try:
            proc.wait(timeout=10)
        except psutil.TimeoutExpired:
            proc.kill()
    except psutil.NoSuchProcess:
        pass
    p.unlink(missing_ok=True)
    return True


def ingest() -> str:
    cmd = raggity_cmd()
    if cmd is None:
        raise RuntimeError(
            "raggity not found — install with `pip install raggity[server]` "
            "or set RIGMA_RAGGITY_CMD")
    cfg = write_rag_config()
    res = subprocess.run([*cmd, "ingest", "--config", str(cfg)],
                         capture_output=True, text=True)
    if res.returncode != 0:
        raise RuntimeError(f"raggity ingest failed:\n{res.stderr or res.stdout}")
    return res.stdout


def retrieve(query: str, k: int = 8, max_context_tokens: int | None = None,
             port: int = RAG_PORT) -> dict:
    r = httpx.post(f"http://127.0.0.1:{port}/retrieve",
                   json={"query": query, "k": k,
                         "max_context_tokens": max_context_tokens},
                   timeout=120)
    r.raise_for_status()
    return r.json()


def ask(question: str, port: int = RAG_PORT) -> dict:
    r = httpx.post(f"http://127.0.0.1:{port}/ask",
                   json={"question": question}, timeout=600)
    r.raise_for_status()
    return r.json()
