from __future__ import annotations

import json
import os
import shlex
import shutil
import subprocess
import time
from pathlib import Path

import httpx
import psutil

from .runtime import rigma_home
from .atomicio import atomic_write_json

RAG_PORT = 11510

# The one sentence every "raggity is missing" path answers with. OD-3: the
# rebuild route returns this verbatim in a 400, and `ingest`/`ensure_sidecar`
# raise it, so the route and the CLI cannot drift apart — the R3-11 lesson was
# that a second hand-maintained copy of a security list is how the bug happened.
RAGGITY_MISSING_MSG = ("raggity not found — install with `pip install "
                       "raggity[server]` or set RIGMA_RAGGITY_CMD")


def rag_dir() -> Path:
    d = rigma_home() / "rag"
    d.mkdir(parents=True, exist_ok=True)
    return d


def _raggity_env(**extra: str) -> dict:
    """raggity's environment. Its Rich output goes to a pipe or a log file, where
    Windows defaults to a strict cp1252: a file name outside it (`ŝ`, CJK, emoji)
    raised UnicodeEncodeError and the ingest or sidecar died. UTF-8 it is, and the
    readers below decode it the same way."""
    return {**os.environ, "PYTHONIOENCODING": "utf-8", **extra}


def raggity_cmd() -> list[str] | None:
    env = os.environ.get("RIGMA_RAGGITY_CMD")
    if env:
        return shlex.split(env, posix=False)
    exe = shutil.which("raggity")
    return [exe] if exe else None


def load_sources() -> list[str]:
    """The configured source folders/globs. Anything that is not a list of
    strings reads as "no sources".

    AUDIT 10-7: sources.json is documented as user-editable ("edit sources via
    `rigma rag add`"), so it can be truncated or hand-edited. Returning the
    parsed value unchecked handed a dict/str/int to add_source (AttributeError
    -> 500 on POST /api/rag/sources) and to the Grounding card's sources.length
    (undefined, so the card said "no folders indexed" while folders WERE
    configured).
    """
    p = rag_dir() / "sources.json"
    try:
        data = json.loads(p.read_text(encoding="utf-8"))
    except Exception:
        return []
    if not isinstance(data, list) or not all(isinstance(x, str) for x in data):
        return []
    return data


def _source_globs() -> list[str]:
    globs = []
    for s in load_sources():
        p = Path(s)
        globs.append(f"{p.as_posix()}/**/*" if p.is_dir() else p.as_posix())
    return globs


def _llm_base_url() -> str:
    """Point the sidecar at whatever port Rigma actually launched on, not a
    hardcoded 11500 (breaks `rigma up --port 8080`)."""
    from . import state as st
    s = st.read_state() or {}
    return f"http://127.0.0.1:{s.get('public_port', 11500)}/v1"


def write_rag_config(llm_base_url: str | None = None) -> Path:
    llm_base_url = llm_base_url or _llm_base_url()
    include = ", ".join(json.dumps(g) for g in _source_globs())
    # AUDIT R3-11: whatever the source folders contain, credentials must not reach
    # the index. Derived from the same denylist the tool read path uses, so a
    # pattern added there is excluded here by construction rather than by memory.
    from .tools import credential_exclude_globs
    exclude = ", ".join(json.dumps(g) for g in credential_exclude_globs())
    index_path = (rag_dir() / "index").as_posix()
    text = (
        "# generated by rigma — do not edit; edit sources via `rigma rag add`\n"
        'profile = "low-ram"\n\n'
        f"[sources]\ninclude = [{include}]\n"
        f"# R3-11: credentials are never indexed, even inside an added folder.\n"
        f"exclude = [{exclude}]\n\n"
        f'[generation]\nbackend = "external"\nbase_url = "{llm_base_url}"\n\n'
        f'[index]\nbackend = "lancedb"\npath = "{index_path}"\n\n'
        '[server]\nauth = "none"\n'
    )
    cfg = rag_dir() / "raggity.toml"
    cfg.write_text(text, encoding="utf-8")
    return cfg


def add_source(path: str) -> list[str]:
    srcs = load_sources()
    ap = str(Path(path).resolve())
    if ap not in srcs:
        srcs.append(ap)
        atomic_write_json(rag_dir() / "sources.json", srcs)
    write_rag_config()
    return srcs


def remove_source(path: str) -> list[str]:
    srcs = load_sources()
    ap = str(Path(path).resolve()) if path else ""
    srcs = [s for s in srcs if s != ap and s != path]
    atomic_write_json(rag_dir() / "sources.json", srcs)
    write_rag_config()
    return srcs


def recorded_sidecar_port() -> int | None:
    try:
        info = json.loads((rag_dir() / "sidecar.json").read_text(encoding="utf-8"))
        return int(info["port"])
    except Exception:
        return None


def _is_raggity_health(body) -> bool:
    """Does this /healthz body come from a raggity sidecar?

    AUDIT R3-10-13: `sidecar_health` accepted ANY local HTTP service that
    answered 200 with parseable JSON, and every decision about document search
    goes through it — `live_sidecar_port` (which advertises
    `search_my_documents` to the model and then POSTs /retrieve and /ask at that
    port), `ensure_sidecar` (which records the answering process's pid in
    sidecar.json), and therefore `stop_sidecar` (which later terminates that
    pid; 10-5 can only check the pid is the one we RECORDED, not that the record
    was written about the right process). The port is not proof of identity:
    ports are recycled, and sidecar.json is a hand-editable file.

    raggity's /healthz carries at least a version and an index backend (see
    tests/fake_raggity_server.py, which mirrors the real shape). An empty or
    unrelated body is treated as "not ours" — a false negative costs a
    restarted sidecar, a false positive hands a stranger the document tool and
    its own termination.
    """
    if not isinstance(body, dict):
        return False
    return bool(body.get("version") or body.get("documents") is not None
                or body.get("index_backend"))


def sidecar_health(port: int = RAG_PORT) -> dict | None:
    try:
        r = httpx.get(f"http://127.0.0.1:{port}/healthz", timeout=3)
        if r.status_code != 200:
            return None
        body = r.json()
    except Exception:
        return None
    return body if _is_raggity_health(body) else None


def _create_time(pid: int) -> float:
    """When this process started, or 0.0 if that cannot be established.

    AUDIT 10-5: a pid alone does not identify a process. Recorded at sidecar
    start so `stop_sidecar` can tell "our sidecar" from "whatever now owns that
    number" — the twin of the 08-1 fix in state.py.
    """
    try:
        if pid <= 0:
            return 0.0
        return float(psutil.Process(pid).create_time())
    except Exception:
        return 0.0


def _looks_like_raggity(proc) -> bool:
    """Does this process's own name/cmdline match the configured raggity
    command? The fallback for a sidecar.json written before created_at existed,
    so an upgrade does not make a live sidecar unkillable."""
    cmd = raggity_cmd()
    if not cmd:
        return False
    want = {os.path.basename(str(c)).lower() for c in cmd if str(c).strip()}
    want.discard("")
    if not want:
        return False
    try:
        argv = {os.path.basename(str(a)).lower() for a in proc.cmdline()}
    except Exception:
        argv = set()
    if want & argv:
        return True
    try:
        return os.path.basename(str(proc.name())).lower() in want
    except Exception:
        return False


def _is_recorded_sidecar(proc, created_at) -> bool:
    """Is `proc` still the raggity sidecar a record was written about?

    AUDIT 10-5: sidecar.json outlives the sidecar it names, and Windows
    recycles pids, so `rigma rag stop` (and shutdown) could terminate an
    unrelated process that inherited the number. A recorded create time must
    still match; with no recorded identity the process's own name/cmdline must
    match the raggity command. Anything unreadable counts as "not ours" — the
    only action gated on this is a kill.
    """
    try:
        want = float(created_at)
    except (TypeError, ValueError):
        want = 0.0
    if want > 0.0:
        try:
            return abs(float(proc.create_time()) - want) < 1.0
        except Exception:
            return False
    return _looks_like_raggity(proc)


def _record_sidecar(pid: int, port: int) -> None:
    try:
        (rag_dir() / "sidecar.json").write_text(
            json.dumps({"pid": pid, "port": port,
                        "created_at": _create_time(pid)}), encoding="utf-8")
    except OSError:
        pass          # a sidecar that is up but unrecorded still answers


def _forget_sidecar() -> None:
    try:
        (rag_dir() / "sidecar.json").unlink(missing_ok=True)
    except OSError:
        pass


# How long to wait for the health endpoint when deciding whether document
# search may be OFFERED. Localhost: a healthy sidecar answers in about a
# millisecond and a dead one refuses instantly, so this only ever bites a
# sidecar that is hung — and for a hung one the answer is no either way.
OFFER_PROBE_SECS = 0.5


def live_sidecar_port(timeout: float = OFFER_PROBE_SECS) -> int | None:
    """The port of a sidecar that is ACTUALLY ANSWERING, or None.

    A different question to `recorded_sidecar_port`, which reports what was
    written to disk. F52: `ensure_sidecar` recorded {pid, port} immediately
    after `Popen` and only then spent up to 90s failing its health check, so the
    file could name a process that never worked. Everything that decided whether
    to OFFER document search read that file, so `search_my_documents` was
    advertised to the model on every turn for a sidecar that had never run —
    while `/api/rag/status`, which asks the port, correctly reported it down. Two
    sources of truth disagreeing is what made it hard to notice.

    So this asks the port, and clears a record that turns out to be stale, so the
    bad file does not outlive the discovery that it is bad.
    """
    port = recorded_sidecar_port()
    if port is None:
        return None
    if sidecar_health(port):
        return port
    _forget_sidecar()
    return None


def ensure_sidecar(port: int = RAG_PORT, timeout: float = 90.0) -> dict:
    health = sidecar_health(port)
    if health:
        return health
    cmd = raggity_cmd()
    if cmd is None:
        raise RuntimeError(RAGGITY_MISSING_MSG)
    cfg = write_rag_config()
    log_path = rag_dir() / "serve.log"
    with open(log_path, "w", encoding="utf-8", errors="replace") as log_f:
        proc = subprocess.Popen(
            [*cmd, "serve", "--config", str(cfg), "--port", str(port)],
            stdout=log_f, stderr=subprocess.STDOUT, env=_raggity_env())
    (rag_dir() / "sidecar.json").unlink(missing_ok=True)
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        if proc.poll() is not None:
            break
        health = sidecar_health(port)
        if health:
            # F52: recorded only NOW, once the process has proved it answers.
            # Writing it straight after Popen made the file a claim about a
            # process that had not started working, and every reader of that
            # claim offered document search on the strength of it.
            _record_sidecar(proc.pid, port)
            return health
        time.sleep(0.5)
    proc.terminate()
    _forget_sidecar()     # F52: never leave a record of a start that failed
    tail = ""
    try:
        tail = "".join(log_path.read_text(encoding="utf-8",
                                          errors="replace").splitlines(True)[-20:])
    except Exception:
        pass
    raise RuntimeError(f"raggity sidecar failed to become healthy on :{port}\n{tail}")


def stop_sidecar() -> bool:
    """Stop the recorded sidecar — but only if it is still that sidecar.

    AUDIT 10-5: the old body terminated `psutil.Process(int(info["pid"]))` with
    no check that the pid was still a raggity sidecar. A record left behind by a
    crash can name the owner's editor, browser or build once Windows recycles
    the number. On a mismatch the record is cleared WITHOUT signalling.
    """
    p = rag_dir() / "sidecar.json"
    try:
        info = json.loads(p.read_text(encoding="utf-8"))
    except Exception:
        return False
    try:
        pid = int(info["pid"])
    except (KeyError, TypeError, ValueError):
        p.unlink(missing_ok=True)
        return False
    proc = None
    try:
        proc = psutil.Process(pid)
    except Exception:
        proc = None          # gone, or not ours to inspect
    if proc is not None and _is_recorded_sidecar(proc, info.get("created_at")):
        try:
            proc.terminate()
            try:
                proc.wait(timeout=10)
            except psutil.TimeoutExpired:
                proc.kill()
        except psutil.NoSuchProcess:
            pass
    p.unlink(missing_ok=True)
    return True


def discover(deep: bool = False, timeout: float = 30.0) -> dict:
    """Document folders raggity found on this machine, for the Grounding card.

    The card used to offer a bare text box, so adding a folder meant typing an
    absolute path from memory. raggity does the looking; this only carries the
    answer across. Never raises: an older raggity has no `discover` command and
    a missing one is not an error, just an empty list — the text box still works.

    RAGGITY_NONINTERACTIVE is set because this is a subprocess with no terminal:
    without it a raggity that decided to prompt would hang until the timeout.
    """
    cmd = raggity_cmd()
    if cmd is None:
        return {"complete": True, "candidates": [], "available": False}
    env = _raggity_env(RAGGITY_NONINTERACTIVE="1")
    argv = [*cmd, "discover", "--json"] + (["--deep"] if deep else [])
    try:
        res = subprocess.run(argv, capture_output=True, text=True,
                             encoding="utf-8", errors="replace",
                             timeout=timeout, env=env)
        if res.returncode != 0:
            return {"complete": True, "candidates": [], "available": False}
        out = json.loads(res.stdout or "{}")
    except (OSError, ValueError, subprocess.TimeoutExpired):
        return {"complete": True, "candidates": [], "available": False}
    out.setdefault("candidates", [])
    out.setdefault("complete", True)
    out["available"] = True
    return out


def ingest() -> str:
    cmd = raggity_cmd()
    if cmd is None:
        raise RuntimeError(RAGGITY_MISSING_MSG)
    cfg = write_rag_config()
    res = subprocess.run([*cmd, "ingest", "--config", str(cfg)],
                         capture_output=True, text=True, encoding="utf-8",
                         errors="replace", env=_raggity_env())
    if res.returncode != 0:
        raise RuntimeError(f"raggity ingest failed:\n{res.stderr or res.stdout}")
    return res.stdout


def rebuild_index() -> str:
    """Throw away the index and build a fresh one from the configured sources.

    OD-3 / R3-11 residual: the credential `exclude` list is written by
    `write_rag_config`, so it only changes a FUTURE ingest. An index built
    before R3-11 still holds whatever was under an added folder — `.env`,
    `.ssh/id_rsa`, `.git-credentials`, browser cookie DBs — and regenerating the
    config does not remove those rows. Deleting the index directory is the only
    way to evict them, so this is a TRUE rebuild rather than a re-ingest.

    ORDER IS LOAD-BEARING — stop -> clear -> ingest:
      1. `stop_sidecar()` first: a running sidecar holds the lancedb index open,
         so deleting the directory under a live server leaves it serving an
         index that no longer exists. A `False` return means there was no
         recorded sidecar, which is not an error.
      2. clear the index directory next, BEFORE the ingest: if ingest ran first,
         raggity would add to the existing rows and the pre-denylist entries
         would survive — the exact thing this exists to remove. `rmtree` is
         deliberately NOT given `ignore_errors=True`: a removal that fails must
         raise so the caller records an error, because a silent failure leaves
         the secrets in place while reporting success.
      3. `ingest()` last: it regenerates `raggity.toml` (and therefore the
         credential excludes) and re-reads the configured sources.

    Never called automatically: `POST /api/rag/reindex` is the only caller,
    because re-reading the owner's documents is the owner's decision (§0.8).
    """
    if raggity_cmd() is None:
        # Before stopping or deleting: with no raggity the rebuild cannot
        # finish, and clearing the index first would leave the owner with
        # neither the old index nor a new one.
        raise RuntimeError(RAGGITY_MISSING_MSG)
    stop_sidecar()
    index_dir = rag_dir() / "index"
    if index_dir.exists():
        shutil.rmtree(index_dir)
    return ingest()


def retrieve(query: str, k: int = 8, max_context_tokens: int | None = None,
             port: int = RAG_PORT) -> dict:
    r = httpx.post(f"http://127.0.0.1:{port}/retrieve",
                   json={"query": query, "k": k,
                         "max_context_tokens": max_context_tokens},
                   timeout=120)
    r.raise_for_status()
    return r.json()


def ask(question: str, port: int = RAG_PORT) -> dict:
    r = httpx.post(f"http://127.0.0.1:{port}/ask",
                   json={"question": question}, timeout=600)
    r.raise_for_status()
    return r.json()
